### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by zayaslui** [zerodahero/laravel-workflow#1]
![Captura de pantalla de 2019-05-16 09-11-55](https://user-images.githubusercontent.com/11598581/57856336-d86aa180-77ba-11e9-8eaf-cd8cfa8f28ff.png)

**Comment by zayaslui** [comment]
First added column currentPlace with dateTime into my model, but not work for me.

**Comment by zayaslui** [comment]
You do not have any demo, where is everything working with laravel 5.8?

**Comment by zerodahero** [comment]
What is your workflow definition?

**Comment by zerodahero** [comment]
If you're using a multiple place workflow, you'll need to cast your marking field to an array:

```php
class BlogPost extends Model
{
     // ...
  
    protected $casts = ['marking' => 'array'];

    // ...
}
```

**Comment by zayaslui** [comment]
My workflow definition

<?php

return [
    'straight'   => [
        'type'          => 'workflow', // or 'state_machine'
        'marking_store' => [
            'type'      => 'multiple_state',
            'arguments' => ['currentPlace']
        ],
        'supports'      => ['App\BlogPost'],
        'places'        => ['draft', 'review', 'rejected', 'published'],
        'transitions'   => [
            'to_review' => [
                'from' => 'draft',
                'to'   => 'review'
            ],
            'publish' => [
                'from' => 'review',
                'to'   => 'published'
            ],
            'reject' => [
                'from' => 'review',
                'to'   => 'rejected'
            ]
        ],
    ]
];

**I try add casts**

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use ZeroDaHero\LaravelWorkflow\Traits\WorkflowTrait;

class BlogPost extends Model
{
	use WorkflowTrait;
   	protected $table = 'blogpost';
   	protected $casts = ['marking' => 'array'];
}

but always the same mistake. :(
