### ISSUE TITLE
Marking store with MorphToMany

### ISSUE THREAD

**Issue by AurelienMendes** [zerodahero/laravel-workflow#13]
Hi,

That's perhaps a little linked with #12  ...

In my application, Post objects are associated to some statuses thanks to a MorphToMany relationship (since not only Post can have statuses, but many other objects).

So I was thinking it is a little redondant to define a "marking" field on my Post model whereas the information already exists in a pivot table (morphToMany) ...
That's when the marking_store like a method could be interesting
```
'marking_store' => [
                'type' => 'method'
                'property' => 'status'
            ],
```
and on the Post model I would imagine the two getter and setter (à la Symfony)
```
public function getStatus(){
    return $this->statusable()->first();
}

public function setStatus($status){
    return $this->statusable()->sync($status)
}
```
But if I write this ticket, it is above all to see if you had other ideas to suggest to me for this problem?

Thanks

**Comment by zerodahero** [comment]
The 'type' of the marking store is for either single or multiple states. In the latest version of this package (v3.0) the requirements are bumped to Symfony v5, which forces the method access from prior versions. (i.e. the "property" is just the common noun for a getter and setter)

So, everything should work as expected, but just a few notes on your comment above:
 - The `type` of marking_store should be either 'single_state' or 'multiple_state'
 - I'm a bit wary of the `setStatus` method you have, since symfony will be passing in a string or array of places (and optionally a context array as the second arg) in which may not be the keys against which you want to sync that relationship.

Let me know if that works, it's a pretty neat idea! I'll close this for now since it doesn't sound like anything is an issue, but feel free to reopen if I'm missing something.

**Comment by AurelienMendes** [comment]
@zerodahero ... as I mention it in the #12  from Symfony 4.3 the `type` value of marking_store could be `method` and the `property` the name of the property to modify (https://symfony.com/blog/new-in-symfony-4-3-workflow-improvements#simpler-configuration). As they mention it, that will be the default from the 5.0 version.

So, theoretically, with a `type`='method' and if my property is 'status', I have to define 2 methods on my model, `getStatus()` and `setStatus()`.
But, as I mention it in #12, and you above, within your package, the type must be 'single_state' or 'multiple_state' ...

I thougth there were no solution for me within your package but when I tried with a `type`= 'single-state' and `property`='status' I has the good surprise to see that the getStatus and setStatus methods are used by the Symfony workflow to get and set the property (status).
So I use them as described in my top message and it works very well.

Here is my complete config:
```
'docsheet_minimal'   => [
        'type'          => 'workflow',
        'metadata'      => [
            'title' => 'Docsheet Status Minimal Workflow',
        ],
        'marking_store' => [
            'type' => 'single-state',
            'arguments' => ['status']
        ],
        'supports'      => [Modules\Docsheet\Models\Docsheet::class],
        'initial_place' => Modules\Docsheet\Models\Docsheet::STATUS_DRAFT,
        'places'        => [
            Modules\Docsheet\Models\Docsheet::STATUS_DRAFT,
            Modules\Docsheet\Models\Docsheet::STATUS_APPLICABLE,
            Modules\Docsheet\Models\Docsheet::STATUS_ARCHIVED,
        ],
        'transitions'   => [
            'set_applicable' => [
                'from' => Modules\Docsheet\Models\Docsheet::STATUS_DRAFT,
                'to'   => Modules\Docsheet\Models\Docsheet::STATUS_APPLICABLE,
            ],
            'set_archived' => [
                'from' => Modules\Docsheet\Models\Docsheet::STATUS_APPLICABLE,
                'to'   => Modules\Docsheet\Models\Docsheet::STATUS_ARCHIVED,
            ]
        ],
    ]
```

**Comment by zerodahero** [comment]
Sorry, I should've been more clear, in the v3.0.0 version of this package, the methodMarkingStore is the only class used for markings, but in prior versions, the method store is not supported.

**Comment by AurelienMendes** [comment]
Correction : there is a typo in my config, `'type' => 'single-state',` instead of `'type' => 'single_state',` but without consequences, since from your code, the MarkingStore instance is a `SingleStateMarkingStore`.

From that, effectively, the $propertyAccessor is never defined, and I don't really understand how I can arrive in my 2 getter and setter methods ...
There is a Laravel "magic" somewhere but not only. Without having defined the getter and setter on the model I don't have errors but the workflow status are wrong, and with the getter and setter defined, I don't have error and the status are fine.

LOL that works but I well understand why ...

**Comment by AurelienMendes** [comment]
Nothing from Laravel ...
That's Symfony itself like a big boy.
In `SingleStateMarkingStore` the method `getMarking()`
There `$this->propertyAccessor->getValue($subject, $this->property)`
Then in `getValue(...)` we go to `$this->readProperty($zval, $propertyPath, $this->ignoreInvalidProperty)[self::VALUE]`
In `readProperty(...)` we arrive in `$this->getReadAccessInfo(\get_class($object), $property)` which do the job to find my getStatus() and setStatus() methods on the model
