### ISSUE TITLE
"The method "App\Models\BlogPost::getMarking()" does not exist."

### ISSUE THREAD

**Issue by devascolades** [zerodahero/laravel-workflow#14]
Hello,

I use your workflow config file example (be careful, 2 comma are missing). and other fields example.
I have the message : 

"The method "App\Models\BlogPost::getMarking()" does not exist." when I do that :

       $post = BlogPost::find(1);
        $workflow = $post->workflow_get();
        $marking = $workflow->getMarking($post);

The property is 'currentPlace' in the config file but in the workflow, I show it is "marking"

        $post = BlogPost::find(1);
        $workflow = $post->workflow_get();
        dd($workflow);

  -markingStore: Symfony\Component\Workflow\MarkingStore\MethodMarkingStore {#364
    -singleState: false
    -property: "**marking**"
  }
  -dispatcher: Symfony\Component\EventDispatcher\EventDispatcher {#331 …3}
  -name: "straight"
}

I  have a field 'currentPlace in my database, I added  another field ('marking') but I have always the same error message .

What is the full path of "use Workflow ;"  ?  I think my app don't find the good way.

I use Laravel 7. It use symfony workflow 5.0.,

**Comment by zerodahero** [comment]
Yes, I'm looking for a good way to tie this in better to the Laravel Models. Symfony expects a simple "getter" format for naming, which Eloquent's magic methods don't follow.

For now, you should add 'getMarking' and 'setMarking' methods on your model to handle this. I'll update here when I find a better way of integrating the two together.

**Comment by zerodahero** [comment]
This is resolved now in v3.0.1. The underlying marking store has been changed to support Eloquent model accessors/mutators.

**Comment by Esrt-Med-Abdessamad** [comment]
[Exemple-de-cahier-des-charges.docx](https://github.com/zerodahero/laravel-workflow/files/6230450/Exemple-de-cahier-des-charges.docx)
[cdc-developpement-logiciel-word.docx](https://github.com/zerodahero/laravel-workflow/files/6230451/cdc-developpement-logiciel-word.docx)
[sample.txt](https://github.com/zerodahero/laravel-workflow/files/6230453/sample.txt)
axsz
