### ISSUE TITLE
Doesn't work with Laravel 6

### ISSUE THREAD

**Issue by Azmeer-crescent** [zerodahero/laravel-workflow#16]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.18.3
    - Conclusion: don't install laravel/framework v6.18.3
    - zerodahero/laravel-workflow 3.x-dev requires illuminate/contracts ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/contracts[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0].
    - zerodahero/laravel-workflow v3.0.0 requires illuminate/contracts ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/contracts[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0].
    - Can only install one of: laravel/framework[7.x-dev, v6.18.3].
    - don't install illuminate/contracts 7.x-dev|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.0|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.1|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.2|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.3|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.4|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.5|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.6|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.7|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.0.8|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.1.0|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.1.1|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.1.2|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.1.3|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.2.0|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.2.1|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.2.2|don't install laravel/framework v6.18.3
    - don't install illuminate/contracts v7.3.0|don't install laravel/framework v6.18.3
    - Installation request for laravel/framework (locked at v6.18.3, required as ^6.3) -> satisfiable by laravel/framework[v6.18.3].
    - Installation request for zerodahero/laravel-workflow ^3.0 -> satisfiable by zerodahero/laravel-workflow[3.x-dev, v3.0.0].

Laravel: 6.18.3   PHP: 7.4.2

**Comment by zerodahero** [comment]
For Laravel v6 and below, please use the 2.x releases.
