### ISSUE TITLE
Use in tracking mode

### ISSUE THREAD

**Issue by nouha97** [zerodahero/laravel-workflow#21]
I tried to use the tracking mode but it still read from the config files , please what is the correct way to use it 
![Screen Shot 2020-06-01 at 11 56 38 PM](https://user-images.githubusercontent.com/49786393/83462894-49cbcf80-a464-11ea-9558-f2c1d9b2bdb3.png)
![Screen Shot 2020-06-02 at 12 00 42 AM](https://user-images.githubusercontent.com/49786393/83462897-4d5f5680-a464-11ea-8174-07a81c70c6df.png)

**Comment by zerodahero** [comment]
When is this being thrown?

Have you tried with an empty `config/workflow.php` (i.e. `return [];`)?

There's some info in the README, here: https://github.com/zerodahero/laravel-workflow#use-in-tracking-mode

I'm thinking this is likely caused by not having any config'd workflows (my original use-case had both), but curious where it's being thrown (on hitting the route (would suggest the registry provider is the culprit) or on loading the workflow into the model (suggesting we're either re-making the registry or there's a bug in there)

**Comment by nouha97** [comment]
yes I've tried with an empty config/workflow.php to see if he keeps loading from the file in the config not from the array that I set

**Comment by nouha97** [comment]
I've tried to keep the array in the config file and I get that :
![Screen Shot 2020-06-02 at 3 42 34 PM](https://user-images.githubusercontent.com/49786393/83533982-2ba7b300-a4e8-11ea-837d-0969ce2bb633.png)

**Comment by nouha97** [comment]
to make the thing more clear , I call this function after a I store a new workflow in my db :
![Screen Shot 2020-06-02 at 3 46 45 PM](https://user-images.githubusercontent.com/49786393/83534274-8ccf8680-a4e8-11ea-861e-715c7549f9a4.png)

**Comment by zerodahero** [comment]
You mentioned that you're calling that after you store the workflow in the DB. How are you loading the workflow before you use it?

Can you post the implementation code that's throwing this?

**Comment by nouha97** [comment]
Thank you for your feedbacks , the problem was simply in the array that I give to the the "addFromArray" function .
the correct one is without the name of the workflow not like the one in the config file .
the correct array : 
 [
    'type' => 'workflow', // or 'state_machine'
    'metadata' => [
        'title' => 'Blog Publishing Workflow',
    ],
    'marking_store' => [
        'type' => 'multiple_state',
        'property' => 'currentPlace'
    ],
    'supports' => ['App\BlogPost'],
    'places' => [
        'review',
        'rejected',
        'published',
        'draft', => [
            'metadata' => [
                'max_num_of_words' => 500,
            ]
        ]
    ],
    'initial_places' => 'draft', // or set to an array if multiple initial places
    'transitions' => [
        'to_review' => [
            'from' => 'draft',
            'to' => 'review',
            'metadata' => [
                'priority' => 0.5,
            ]
        ],
        'publish' => [
            'from' => 'review',
            'to' => 'published'
        ],
        'reject' => [
            'from' => 'review',
            'to' => 'rejected'
        ]
    ],
];
thank you again..

**Comment by zerodahero** [comment]
Glad you were able to resolve that! I'll add a note in the readme so others are aware as well. Thanks!

**Comment by nouha97** [comment]
It will be good !
Thank you ..
