### ISSUE TITLE
Column not found. Unknown column 'marking'

### ISSUE THREAD

**Issue by sica07** [zerodahero/laravel-workflow#24]
First of all, thank you for your work!
When I'm trying to persist the state, I'm getting the above error. 
```php

$workflow->apply($post, 'to_review');
$post->save();
//Result: Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054Unknown column 'marking' in 'field list'
```
It seems that I should add some new columns to the DB tables. 
Are there any other columns (beside `marking`) that should be added?
Also, I think that it would be useful to specify this in the documentation.

**Comment by zerodahero** [comment]
Hi! In the config, the `marking_store.property` field defines what column you're using on your model. This will be the place that the workflow will record what state it's in, so if you're calling it something different ("status", "state", etc) you can change that in the config.

Give that a shot, if you're still having issues, can you post your workflow config?

**Comment by sica07** [comment]
Hi! It worked. Thank you for your help!
