### ISSUE TITLE
get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by zayaslui** [zerodahero/laravel-workflow#3]
![Captura de pantalla de 2019-05-23 11-26-43](https://user-images.githubusercontent.com/11598581/58265477-c1ddc080-7d4d-11e9-9e47-85ba40402322.png)

**MY ROUTE**
Route::get('/workflow', 'BlogPostController@index');

my composer.json

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "zerodahero/laravel-workflow": "^2.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**MY MIGRATION BLOGPOST**
`<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTableBlogPost extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('blogpost', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
            $table->string('description');
           $table->dateTime('currentPlace');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('blogpost');
    }
}
`
**INSERT INTO BLOGPOST**
insert into blogpost(id,description,created_at,updated_at)values(1,'descripcion',now(),now());

**MY CONTROLLER BLOGPOST**

< ? php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Workflow;
use App\BlogPost;

class BlogPostController extends Controller
{

    public function index()
    {
            $post = BlogPost::find(1);
            $workflow = Workflow::get($post);
            // if more than one workflow is defined for the BlogPost class
            // $workflow = Workflow::get($post, $workflowName);

            //$workflow->can($post, 'publish'); // False
            $workflow->can($post, 'to_review'); // True
            $transitions = $workflow->getEnabledTransitions($post);

            // Apply a transition
            $workflow->apply($post, 'to_review');
            $post->save(); // Don't forget to persist the state

            // Using the WorkflowTrait
            $post->workflow_can('publish'); // True
            //$post->workflow_can('to_review'); // False

            // Get the post transitions
            foreach ($post->workflow_transitions() as $transition) {
                echo $transition->getName();
            }

            // Apply a transition
            $post->workflow_apply('publish');
            $post->save();        
    }

}

**Comment by zerodahero** [comment]
Is `BlogPost::find()` returning the correct model? That error in the screenshot is from the symfony component itself--the facade is passing along the object, which appears to be `null` in your case.

**Comment by zayaslui** [comment]
I change workflow definition.
  'type'      => 'single_state',

and migration

$table->string('currentPlace');
