### ISSUE TITLE
The method "App\Models\BlogPost::getCurrentPlace()" does not exist.

### ISSUE THREAD

**Issue by liuyong888** [zerodahero/laravel-workflow#30]
Environment:
  Laravel Framework version 7.12.0;
  "zerodahero/laravel-workflow": "3.0";

This is my code and error report:
<img width="1787" alt="Snipaste_2020-10-27_23-55-05" src="https://user-images.githubusercontent.com/45752479/97327417-e6798880-18af-11eb-9e08-48dbf8e110ea.png">

Tips: I also found some code in (https://symfony.com/doc/current/workflow.html#installation)
<img width="536" alt="Snipaste_2020-10-28_00-00-20" src="https://user-images.githubusercontent.com/45752479/97328081-9b13aa00-18b0-11eb-8a91-0d792f995045.png">
**### Do I need to add the code myself? I don't see these methods in the example**
I am a novice. Please tell me this!
@zerodahero

**Comment by zerodahero** [comment]
I'd recommend starting with updating this package to v3.2.0. On Laravel 7, that should be no problem for you to do (please let me know if that's not the case!). In v3.0, the only marking store available is the default Symfony marking store, in which case, yes you will need to add `getCurrentPlace()` and `setCurrentPlace` to your model.

In version v3.0.1 of this package, I introduced an Elqouent version which is the new default. It will use the native Eloquent setters/getters for this, so there should be no need for adding any other methods (unless you need the transition context).

Let me know how that works out!

**Comment by liuyong888** [comment]
> I'd recommend starting with updating this package to v3.2.0. On Laravel 7, that should be no problem for you to do (please let me know if that's not the case!). In v3.0, the only marking store available is the default Symfony marking store, in which case, yes you will need to add `getCurrentPlace()` and `setCurrentPlace` to your model.
> 
> In version v3.0.1 of this package, I introduced an Elqouent version which is the new default. It will use the native Eloquent setters/getters for this, so there should be no need for adding any other methods (unless you need the transition context).
> 
> Let me know how that works out!

Hi Zack, thank you very much for your reply! For the above problem, I tried the latest version v3.2.0 is OK.
I recently have a project management system that needs to introduce the concept of workflow. This is my first contact with workflow and I cannot understand it. There is no right thought to guide me, so I can't imagine it. I read "zerodahero/laravel-workflow-example" and there is nothing I want. Can you send me a comprehensive application package example about workflow. Please, here my email address: liuyong_0556@qq.com
I will always pay attention!
thank you!

**Comment by zerodahero** [comment]
Hi @liuyong888, glad to hear that v3.2.0 works for you!

Workflows can be a bit tricky to implement in projects sometimes. I'd recommend taking a look at these resources to better understand the Symfony Workflow component (this package just adds an adapter for Laravel to integrate more easily with it):

https://symfony-workflow-demo.herokuapp.com/
https://symfony.com/doc/current/components/workflow.html

For workflows in general, Wikipedia was actually the most help for me, conceptually when I was first learning about these. The term you'll likely want to look up first is "Petri Net":

https://en.wikipedia.org/wiki/Petri_net

As for workflows in projects, like all packages, I'd advise you to only reach for a package/library when you _need_ it. The two main benefits of using the workflow component are (1) having more control over applying and guarding transitions, (2) eventing and working with workflow events asynchronously. In other words, be critical in deciding whether your project's flow _needs_ a relatively rigid system to control it. A lot of workflows don't need the transition capabilities, and a "status" column and a bit of logic can handle things much more easily.

Hope that helps! I maintain this package in my spare time, so sending a comprehensive application package is outside the scope of what I'm able to help with here. Hope these resources help!
