### ISSUE TITLE
Argument 1 passed to ZeroDaHero\LaravelWorkflow\WorkflowRegistry::__construct() must be of the type array, null given, called in /var/www/html/vendor/zerodahero/laravel-workflow/src/WorkflowServiceProvider.php

### ISSUE THREAD

**Issue by codeDude64** [zerodahero/laravel-workflow#32]
# Error when I use workflow_get();

I'm in a team that we are using your software to manage a workflow. A partner created the workflow and tested in a call and all it works!! But when I pulled the branch where there the code that works and then typed in console `composer install` to download the lib, in my side didn't work, Laravel shows 

`Argument 1 passed to ZeroDaHero\LaravelWorkflow\WorkflowRegistry::__construct() must be of the type array, null given, called in /var/www/html/vendor/zerodahero/laravel-workflow/src/WorkflowServiceProvider.php`

**The different here is the error say ...null given...**

Notes: 
* We are using a docker container, so I think that the env is not the problem.
* the marking_store type is multiple_state.
* We are using Laravel 6.2 and your lib in 2.0 version

**Comment by zerodahero** [comment]
Env is probably the culprit here, since those arguments are the config. Looks like in the 2.0 branch, you'll need both configs (`workflow` and `workflow_registry`) defined (as normal config arrays). Are both configs setup?

**Comment by codeDude64** [comment]
@zerodahero There are the both configs file in my branch (`workflow` and `workflow_registry`). I don't know if I must to do something in console to workflow lib admits both config file.
it seems that the workflow receive null in both arguments.

![image](https://user-images.githubusercontent.com/35637860/99817307-604d0c80-2b12-11eb-8e1d-2c6e130166ff.png)

**Comment by zerodahero** [comment]
Yeah, definitely seems env-related. Have you tried `php artisan config:clear`?

**Comment by codeDude64** [comment]
Great, it worked !! Thank you
