### ISSUE TITLE
Apply transitions does not work if place value is 0

### ISSUE THREAD

**Issue by realadilet** [zerodahero/laravel-workflow#37]
my config like this

`'places'        => [
            0,
            1,
            2,
            4,
],`

place 0 does not work because of this line

https://github.com/zerodahero/laravel-workflow/blob/develop/src/MarkingStores/EloquentMarkingStore.php#L36

maybe here you need to do it differently.

like 

`if (! $marking && $marking !== 0) {
      return new Marking();
  }
`

**Comment by realadilet** [comment]
@zerodahero

**Comment by klimenttoshkov** [comment]
You are not supposed to use type of numbers in place name. Try casting them to string: `['0','1','2','4',]`

**Comment by realadilet** [comment]
> You are not supposed to use type of numbers in place name. Try casting them to string: `['0','1','2','4',]`

thanks, but it didn't work.

```php
$value = '0';
if (!$value) {
    echo 'false';
} else {
     echo 'true';
}
```
also returns false

**Comment by klimenttoshkov** [comment]
Because '0' is typecasted to 0 prior to performing boolean operation. I suggest you refactor your code appropriately. This broad approach will backfire at you. What exactly are you checking with this.

**Comment by realadilet** [comment]
> Because '0' is typecasted to 0 prior to performing boolean operation. I suggest you refactor your code appropriately. This broad approach will backfire at you. What exactly are you checking with this.

I can't refactor the code right now, I have to change a lot, I'm looking for a quick solution.

**Comment by realadilet** [comment]
rather, I will have to fork and change the condition.

**Comment by zerodahero** [comment]
@adiletmaks , yeah, we could make that check in the `EloquentMarkingStore` class a bit more type-safe. I'll try to add that in soon, but if you've already got a fork with the changes, feel free to open a PR.

**Comment by zerodahero** [comment]
@adiletmaks had a quick moment, and pushed it up to develop. Give that a shot a let me know if it solves your issue. I'll be pushing a release here soon (in the next few days most likely)

**Comment by realadilet** [comment]
> @adiletmaks had a quick moment, and pushed it up to develop. Give that a shot a let me know if it solves your issue. I'll be pushing a release here soon (in the next few days most likely)

oh, thanks, this will solve my problem. I'm waiting for the release.
