### ISSUE TITLE
helper as symfony (i.e.: workflow_transition_blockers)

### ISSUE THREAD

**Issue by zofe** [zerodahero/laravel-workflow#49]
Hi all, 
I'm really grateful for  this package.
I am trying to recreate some twig/blade helpers  from Symfony described here  https://symfony.com/doc/current/workflow.html

I.e.:
```
function workflow_metadata($object, $meta, $place_or_transition)
{
    $workflow = $object->workflow_get();
    return $workflow->getMetadataStore()->getMetadata($meta,$place_or_transition);
}
...

```

but I need some help to create **workflow_transition_blockers**
to display current blocking message that prevent to apply "next" transition on a simple state_machine workflow.

Has someone already done it? or may help with some suggestion?

**Comment by zerodahero** [comment]
Hi @zofe !

Looks like you're on the right track already. The transition blocker list is fairly similar to the metadata, I would probably start with something like this:

```php
function workflow_transition_blockers(Model $subject, string $transition): TransitionBlockerList
{
    $workflow = $subject->workflow_get();
    return $workflow->buildTransitionBlockerList($subject, $transition);    
}
```
That's going to return a `Symfony\Component\Workflow\TransitionBlockerList` for that transition. That class allows for iteration over the list (like in a `foreach`), so in blade, you might have something like:

```blade
@foreach (workflow_transition_blockers($subject, $transition) as $blocker)
<li class="error">{{ $blocker->getMessage() }}</li>
@endforeach
```

Try that out and let me know how it goes!

**Comment by klimenttoshkov** [comment]
@zerodahero 

Can you somehow extend the documentation to cover this?
I know it is based on methods that are in Symfony workflow, but anyway... At least point out the most important parts.

**Comment by zofe** [comment]
Exactly what I was looking for, you're  precious zack.
It works.
