### ISSUE TITLE
A understandable Example

### ISSUE THREAD

**Issue by sjavadez** [zerodahero/laravel-workflow#5]
Hi,

Is there Example project for creating workflow engine in laravel via this package Like [This](https://github.com/lyrixx/SFLive-Paris2016-Workflow) for symfony ?

[Symfony project Demo](https://symfony-workflow-demo.herokuapp.com/)

I don't understand how to use state machine and events .

Thanks For great Supports.

**Comment by zerodahero** [comment]
This package really only provides a "Laravel flavored" way of using the Symfony workflow component, so any example in Symfony effectively is the same. With this package, you can use the Laravel event listeners (or subscribers, as I often do for this) to listen to the events fired from the workflow.

I'll add it to my list to add in a simple and understandable example, but it will likely take a while for that to make it to the top of my list. I'd gladly take pull requests if anyone else wants to take that on.

**Comment by zerodahero** [comment]
Here's a very basic working example of using the package. https://github.com/zerodahero/laravel-workflow-example
