### ISSUE TITLE
Marking_store configuration option should be removed

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#58]
I suggest to remove from documentation and configuration files `marking_store` because it is inferred based on workflow type. You can check [check details here](https://github.com/symfony/symfony/issues/45352)

**Comment by zerodahero** [comment]
Thanks! I've removed this in the docs and config files starting in v4.0

**Comment by zerodahero** [comment]
This was addressed in [v4.0.0](https://github.com/zerodahero/laravel-workflow/releases/tag/v4.0.0), please let me know if there's still any issues remaining for this.
