### ISSUE TITLE
Wrong events fired when using transition from two places to one

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#59]
For this workflow
![straight](https://user-images.githubusercontent.com/59835221/153163589-263d0c60-13a9-498b-a460-7c4d851a19c8.png)

we have a listener that dumps the events fired. There is extra `entered.c` event emitted.

Transitions:
```
        $this->info ('Apply T1');
        $workflow->apply($model, 't1');
        
        $this->warn(print_r ($model->marking, true));
        
        $this->info ('Apply T4');
        $workflow->apply($model, 't4');
        $this->warn(print_r ($model->marking, true));
```

Output:
```
Apply T1
string(26) "workflow.straight.guard.t1"
string(25) "workflow.straight.leave.a"
string(31) "workflow.straight.transition.t1"
string(25) "workflow.straight.enter.b"
string(25) "workflow.straight.enter.c"
string(27) "workflow.straight.entered.b"
string(27) "workflow.straight.entered.c"
string(30) "workflow.straight.completed.t1"
string(26) "workflow.straight.guard.t4"
string(26) "workflow.straight.guard.t4"
string(29) "workflow.straight.announce.t4"
string(29) "workflow.straight.announce.t4"
Array
(
    [b] => 1
    [c] => 1
)

Apply T4
string(26) "workflow.straight.guard.t4"
string(26) "workflow.straight.guard.t4"
string(25) "workflow.straight.leave.b"
string(31) "workflow.straight.transition.t4"
string(25) "workflow.straight.enter.d"
string(27) "workflow.straight.entered.c"
string(27) "workflow.straight.entered.d"
string(30) "workflow.straight.completed.t4"
string(26) "workflow.straight.guard.t4"
string(29) "workflow.straight.announce.t4"
string(25) "workflow.straight.leave.c"
string(31) "workflow.straight.transition.t4"
string(25) "workflow.straight.enter.d"
string(27) "workflow.straight.entered.d"
string(30) "workflow.straight.completed.t4"
Array
(
    [d] => 1
)
```

**Comment by klimenttoshkov** [comment]
Workflow definition:

```
    'straight' => [
        // 'type' => 'state_machine',
        'type' => 'workflow',
        'supports' => [TestModel::class],
        'initial_places' => ['a'],
        'places' => [
            'a','b', 'c', 'd',
        ],
        'transitions' => [
            't1' => [
                'from' => 'a',
                'to' => ['b', 'c'],
            ],
            't4' => [
                'from' => ['b','c'],
                'to' => 'd',
            ],
            
        ],
    ],
```

**Comment by zerodahero** [comment]
Looks like this was due to the definition creating two transitions for a workflow instead of one (it was creating a workflow for each "from" instead of for _both_). I've pushed a change into the `develop` branch. Can you give that a try and see if that resolves this?

**Comment by klimenttoshkov** [comment]
I am using dev-develop, don't seem to make any difference:

having the same setup as described above, this is the list of generated events:

```
Apply T1
workflow.straight.entered.a
workflow.straight.guard.t1
workflow.straight.leave.a
workflow.straight.transition.t1
workflow.straight.enter.b
workflow.straight.enter.c
workflow.straight.entered.b
workflow.straight.entered.c
workflow.straight.completed.t1
workflow.straight.guard.t4
workflow.straight.guard.t4
workflow.straight.announce.t4
workflow.straight.announce.t4
Apply T4
workflow.straight.guard.t4
workflow.straight.guard.t4
workflow.straight.leave.b
workflow.straight.transition.t4
workflow.straight.enter.d
workflow.straight.entered.c
workflow.straight.entered.d
workflow.straight.completed.t4
workflow.straight.guard.t4
workflow.straight.announce.t4
workflow.straight.leave.c
workflow.straight.transition.t4
workflow.straight.enter.d
workflow.straight.entered.d
workflow.straight.completed.t4
```

**Comment by zerodahero** [comment]
I may need to revert this, since it breaks the previous convention of "any of the places" vs "all of these places". Without this change, it would be necessary to specify the workflow as:
```php
    'straight' => [
        // 'type' => 'state_machine',
        'type' => 'workflow',
        'supports' => [TestModel::class],
        'initial_places' => ['a'],
        'places' => [
            'a','b', 'c', 'd',
        ],
        'transitions' => [
            't1' => [
                'from' => 'a',
                'to' => ['b', 'c'],
            ],
            't4' => [
                'from' => [
                    ['b','c'] // Note the array of arrays
                ],
                'to' => 'd',
            ],
            
        ],
    ],
```
Which would specify that `t4` is a transition from _both_ `b` and `c` to `d`, _not_ a transition from _either_ `b` or `c` to `d` (which would leave twice)

**Comment by klimenttoshkov** [comment]
Right now in this specific case there is no difference, more like it's a mess.

After applying T1, there are two Announce T4 events.
After applying T4 and Leaving B is causing emit of Enter C, which is wrong because we are already there (in C).
Then we have the doubled D.

But I'm not sure if this is a problem from the workflow component itself, or something with this package? Can you share your opinion please.

**Comment by zerodahero** [comment]
Specifically with the events, this may be related to the workflow component. The only possibility with this package is that the config definition doesn't match the same way that Symfony builds the definition, which would create the discrepancy between the "any of these places transition to..." and "all of these places transition to..." scenarios.

It would probably be best to at least try this out in a pure Symfony environment to confirm that, but so far since both ways yield the same result for you, I lean toward this being a characteristic of the workflow component itself.

**Comment by klimenttoshkov** [comment]
Actually the problem was in my configuration. Even though I have paid double and triple attention, transition from [b,c] was not encoded in double array, resulting in separate transitions from `b` and `c` to `d` instead of one (as I expected to be).

It is pretty obvious by the code snippets above and the dump, but somehow I overlooked it.

Here is a dump of the properly defined workflow and then transitions and events are fired just as expected:
```
Apply T1
workflow.straight.entered.a
workflow.straight.guard.t1
workflow.straight.leave.a
workflow.straight.transition.t1
workflow.straight.enter.b
workflow.straight.enter.c
workflow.straight.entered.b
workflow.straight.entered.c
workflow.straight.completed.t1
workflow.straight.guard.t4
workflow.straight.announce.t4
Apply T4
workflow.straight.guard.t4
workflow.straight.leave.b
workflow.straight.leave.c
workflow.straight.transition.t4
workflow.straight.enter.d
workflow.straight.entered.d
workflow.straight.completed.t4
```
![straight](https://user-images.githubusercontent.com/59835221/155294647-2591feda-7483-49e1-85f2-09971c8f1ca9.png)

You may safely close the issue. Thank you
