### ISSUE TITLE
workflow_apply second parameter

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#61]
Hi,

In case I want to use the trait and send context to transition, i have to use all three parameters to workflow_apply.
However second parameter is irrelevant, because the trait is directly applied to given model.
I propose to remove the second parameter and leave context to be second optional argument.

**Comment by zerodahero** [comment]
I like this suggestion, but it could be a pretty substantial breaking change for some. For now, I'd suggest using named parameters. I'll take a closer look at a way to avoid the breaking change.

**Comment by zerodahero** [comment]
Added some duck-typing support for this, currently in `develop`.
