### ISSUE TITLE
Dependency injection in listeners

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#62]
Hello,

I have tried to define a listener with second parameter of arbitrary type, using dependency injection.
Attempt to call it fails because the listener function is called with one parameter only (the type of Event).

is it possible to add support for dependency injection?

**Comment by zerodahero** [comment]
I'm not sure I understand how this issue is related to the package? Sounds like just a matter of defining what the container should be injecting to the listener--which is all in the Laravel framework.

**Comment by klimenttoshkov** [comment]
It is not related and this is my mistake, that I apologize for.

I was expecting DI to work directly on subscriber methods. That's my fault. Please close.
