### ISSUE TITLE
$event->stopPropagation(); does not work

### ISSUE THREAD

**Issue by klimenttoshkov** [zerodahero/laravel-workflow#64]
In any workflow subscriber when calling `$event->stopPropagation();` it does nothing. All further events are called.

**Comment by zerodahero** [comment]
`stopPropagation()` looks like a feature specific to Symfony. In Laravel, it would be the responsibility of the listener to do so: https://laravel.com/docs/9.x/events#stopping-the-propagation-of-an-event

Is there something specific to this package in that regards that I'm missing?

**Comment by klimenttoshkov** [comment]
Calling it should stop Symfony from emitting the rest of the events. At least I thought so.

Having a subscriber and returning `false` from any of it's methods does not prevent the rest of the events.

I am not sure if this is package related. In case we can call the original stopPropagation() and this to lead to Symfony not generating the rest of the events – then maybe you can help?

**Comment by klimenttoshkov** [comment]
`stopPropagation()` causes Symfony Workflow not to generate the rest of the events for the workflow. This is not the same as stopping one event from bubbling up.

**Comment by zerodahero** [comment]
It looks like it's a similar mechanism in Symfony as to Laravel--the `stopPropagation()` method just prevents future event listeners from listening to the event--it doesn't stop the events themselves from being fired.

**Comment by klimenttoshkov** [comment]
You are right. I had wrong expectations. Please close.
