### ISSUE TITLE
define workflow inside model class

### ISSUE THREAD

**Issue by somethingweird** [zerodahero/laravel-workflow#7]
Is it possible to define the workflow inside the model?

I'm currently executing
```php
Workflow::get($post, $workflowName);
```

Is it possible to do something like this
```php
$post->workflow_get($workflowName)
$post->refresh();
```

This way I don't have to load Workflow into the controller, and just the model itself.

**Comment by zerodahero** [comment]
Yeah, that's a good idea, and would be easy enough to add in the the trait!
I'll get that in there and release it next week.

**Comment by somethingweird** [comment]
Thanks!

**Comment by zerodahero** [comment]
This is added in to the trait in version v2.0.4
