### ISSUE TITLE
Install on L9

### ISSUE THREAD

**Issue by invaders-xx** [zerodahero/laravel-workflow#74]
I am unable to install the package on L9. Composer returns:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires zerodahero/laravel-workflow ^4.0 -> satisfiable by zerodahero/laravel-workflow[v4.0.0, v4.0.1, v4.0.2, v4.0.3].
    - zerodahero/laravel-workflow[v4.0.0, ..., v4.0.3] require symfony/event-dispatcher-contracts ^2.4 -> found symfony/event-dispatcher-contracts[v2.4.0, ..., 2.5.x-dev] but the package is fixed to v3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require zerodahero/laravel-workflow:*" to figure out if any version is installable, or "composer require zerodahero/laravel-workflow:^2.1" if you know which you need.

Any idea how to solve ?

**Comment by soap** [comment]
I confirmed that I can generate this error. To work around, you have to use with --with-all-dependencies.

`composer require zerodahero/laravel-workflow --with-all-dependencies`

I use above command and installation was successful.
I will create PR to resolve this error.

**Comment by invaders-xx** [comment]
composer require zerodahero/laravel-workflow --with-all-dependencies not working for me
Problem 1
    - Root composer.json requires zerodahero/laravel-workflow ^4.0 -> satisfiable by zerodahero/laravel-workflow[v4.0.0, v4.0.1, v4.0.2, v4.0.3].
    - zerodahero/laravel-workflow[v4.0.0, ..., v4.0.3] require symfony/event-dispatcher-contracts ^2.4 -> found symfony/event-dispatcher-contracts[v2.4.0, ..., 2.5.x-dev] but it conflicts with your root composer.json require (^3.0).

**Comment by zerodahero** [comment]
Looks like the contracts bumped a major version, which wasn't allowed by this package. @soap 's fix should address this, it's been pushed out at v4.0.4

Let me know if you still run into any issues with this!

**Comment by invaders-xx** [comment]
Fixed, thanks Guys!
