### ISSUE TITLE
Support for Laravel 11?

### ISSUE THREAD

**Issue by nileshd** [zerodahero/laravel-workflow#92]
Can you please add support for Laravel 11

**Comment by juliangums** [comment]
That would be great

**Comment by juliangums** [comment]
I pulled it from this branch https://github.com/zerodahero/laravel-workflow/pull/91 but I am getting this error (same that is mentioned in the checks):
`Declaration of ZeroDaHero\LaravelWorkflow\MarkingStores\EloquentMarkingStore::setMarking(object $subject, Symfony\Component\Workflow\Marking $marking, array $context = []) must be compatible with Symfony\Component\Workflow\MarkingStore\MarkingStoreInterface::setMarking(object $subject, Symfony\Component\Workflow\Marking $marking, array $context = []): void`

**Comment by juliangums** [comment]
added this pr to fix it https://github.com/zerodahero/laravel-workflow/pull/93

**Comment by juliangums** [comment]
@zerodahero so if you pull in https://github.com/zerodahero/laravel-workflow/pull/91 and https://github.com/zerodahero/laravel-workflow/pull/93 this should all be sorted and the package is compatible with Laravel 11 and the latest Symfony workflow version from what I can see.

**Comment by zerodahero** [comment]
Released with v5: https://github.com/zerodahero/laravel-workflow/releases/tag/v5.0.0
